pipeline {
  agent {
    docker {
      image 'docker:18.05-dind'
      label 'bob-epic-jenkins-agent'
      registryUrl 'https://registry.hub.docker.com'
      registryCredentialsId 'docker-hub'
    }
  }
  stages {
    stage("login docker") {
      steps {
        dir("service-a") {
          sh "docker login"
        }
      }
    }
    stage("build docker image") {
      steps {
        dir("service-a") {
          sh "docker image build -t bobxmasnone/bob-epic-repository:service-a"
        }
      }
    }
    stage("push docker image") {
      steps {
        dir("service-a") {
          sh "docker push bobxmasnone/bob-epic-repository:service-a"
        }
      }
    }
  }
}