pipeline {
  agent {
    docker {
      image 'docker:18.05-dind'
      registryUrl 'https://registry.hub.docker.com'
      registryCredentialsId 'docker-hub'
    }
  }
  stages {
    stage("login docker") {
      steps {
        sh "echo $pwd"
        sh "docker login"
      }
    }
    stage("build docker image") {
      steps {
        sh "docker image build -t bobxmasnone/bob-epic-repository:service-a"

      }
    }
    stage("push docker image") {
      steps {

        sh "docker push bobxmasnone/bob-epic-repository:service-a"

      }
    }
  }
}